### ISSUE TITLE
<NA> coefficient labels

### ISSUE THREAD

**Issue by mcdjork** [jaredhuling/bigFastlm#1]
I have a data set of about a million rows. 
variable c is a factor.

````
data <- model.matrix(~ poly(a,5,raw=TRUE) *  poly(b,5,raw=TRUE) + c)
bigMatrix <- data %>% bigmemory::as.big.matrix()
bigLmObj <- bigFastlm::bigLm(bigMatrix,y)
bigLmObj$coefficients %>% broom::tidy()
````

The output of this is as follows (all remaining names are <NA>):

   .|names|x
------|-----|----
1  |`poly(a, 5, raw = TRUE)1` | -80151.370
2  |                   `<NA>` |-172198.658
3   |                  `<NA>` | 156478.496
4    |                 `<NA>` | -12278.055
5    |                 `<NA>` | -13127.687
6    |                 `<NA>` |   2495.194
7     |                `<NA>` | 197746.762
8    |                 `<NA>` |-171130.880
9    |                 `<NA>` |  68724.827
10  |                  `<NA>` | -13133.288
... with 30 more rows 

Have I done something wrong, or is there a bug where the covariate labels are dropped?

Thank you.

**Comment by jaredhuling** [comment]
Thanks for the pointer. I think I've fixed the issue with the latest update

**Comment by mcdjork** [comment]
Works great, thank you!
